# Basic Input and Output
video_path: "inputs/gBR_sFM_c01_d04_mBR4_ch05.mp4"
output_dir: "outputs"

# Model and Inference
model_name: "D:/WorkSoftware/pycharm/PyCharm 2024.1.3/projects/dancepose/models/yolov8s-pose.pt"   # Optional yolov8n/s/m/l/x-pose.pt
device: "0"                     # GPU: "0" or "cpu"
imgsz: 640
conf: 0.25
iou: 0.50
vid_stride: 1                   # Inference every few frames, 1 means every frame

# Visualization
save_overlay: true
overlay_fps: null               # null = Use the source video FPS
kp_score_thresh: 0.35
line_thickness: 2
point_radius: 3
smooth_window: 5                # Used only for slight overlay smoothing; 0 = no smoothing.
